### ISSUE TITLE
Резюме по 1-му ревью.

### ISSUE THREAD

**Issue by irinamozes** [ArtofWASD/react-burger#1]
Проект очень неплохой.

Компоненты заданы в виде функциональных компонент.

Учтено, что в регистрозависимых операционных системах, таких как Linux, например, важно, чтобы регистр букв названий файлов и папок в файловой структуре проета совпадал с регистром букв в их названиях при указании пути в инструкциях импорта в коде js. Проект в регистрозависимых операционных системах собирается и компилируется.

Что нужно подкорректировать для возможности правильного выполнения следующих этапов и спринтов.

1. Правила css для компонент должны быть помещены в css - модули. Сейчас у Вас файлы с правилами css находятся в глобальной области видимости проекта. В больших проектах, которые пишутся не одним человеком, в таких файлах могут встретиться одинаковые названия селекторов, имеющих разный смысл. В этом случае может возникнуть
незапланированное переопределение правил css для этих селекторов, что приведёт к ошибочной работе приложения.
О css-модулях прочитайте в Ваших лекциях с тренажёрами для 1-го спринта.  В глобальной области проекта, может находиться только один файл, index.css и содержать общие правила для всех элементов, если такие нужны.

2. Компонента App такая же компонента, как и другие. Её нужно поместить с её файлом и с файлом css  в свою папку app в папку components.
При этом её файл css нужно также сделать модульным, а общие стили (если они есть), относящиеся ко всем компонентам, нужно поместить в файл index.css.

3. Данное с дефолтным массивом ингредиентов const data нужно импортировать в родительской компоненте ( App) и передавать компонентам  BurgerIngredients и BurgerConstructor в качестве значения атрибута этих компонент при их рендере в родительской компоненте. Это сделать необходимо, так как уже на следующем этапе получать исходный массив ингредиентов нужно будет с сервера и обязательно в родительской компоненте самого высокого уровня при загрузке сайта, для того, чтобы он был доступен сразу на всех страницах проекта, так как на следующих спринтах в проекте будет несколько страниц, а не одна, как сейчас.

4. Нужно сделать развёрнутую проверку типов пропсов (не только на то, что данное объект или массив. Нужно сделать проверку каждого поля объекта ингредиента или каждого поля объекта-элемента массива ингредиентов) во всех компонентах, в которые эти данные поступают как пропсы, при этом проверка должна быть и на правильность типа данных, и одновременно на наличие этих данных (isRequired).
Такую проверку можно сделать с помощью библиотеки PropTypes, прочитайте о ней ещё раз  в Ваших лекциях с тренажёрами, которые относятся к 1-му этапу 1-го спринта.
Нужно сделать развёрнутую проверку типов пропсов во всех компонентах, которые имеют пропсы, независимо от того, проверялись ли уже аналогичные данные в других компонентах.
Можно сократить запись проверки типов в каждой компоненте, поместив в какую-нибудь константу часть записи проверки, которая встречается в нескольких компонентах.
Например, переменную const menuItemPropTypes можно поместить в файл constants.js в папке utils в src и импортировать её оттуда во все компоненты, где Вы проверяете свойства, указанные в ней у различных пропсов:
```
const menuItemPropTypes = PropTypes.shape({
    _id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    calories: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
    image: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    __v: PropTypes.number.isRequired,
 });
```
5. Нужно исправить вёрстку. По заданию требуется, чтобы в самом верху бургера и в самом низу были булки одного типа и на них были иконки с замком. При этом на верхней булке должно быть написано (верх), а на нижней - (низ). Между булками могут быть любые другие ингредиенты, кроме булок, и на них должны быть иконки корзинок удаления.

6. Скроллбар окна конструктора бургера не должен распространяться на заблокированные слои бургера (на слои с замком). СМ. снимок, как должна выглядеть главная страница:
![Снимок экрана в 2022-03-01 00-58-52](https://user-images.githubusercontent.com/19558891/159166559-2fdd3d8d-485b-4df9-85fe-0b765ffbc3bf.png)

Что можно лучше.

1. Атрибут style вводить элементам размётки не рекомендуется, так как, имея наивысший приоритет, этот атрибут может неконтролируемо переопредилить стили,
заданные в файлах css. Все правила css, относящиеся к какой-то компоненте, нужно помещать в её модульный файл css.

2. Лучше имена папок и файлов проекта задавать в стиле kebab-case.
Какие бывают стили в названиях файлов js и зачем они нужны, кратко написано здесь:
https://medium.com/@alivander/camel-pascal-snake-case-и-другие-стили-написания-288ec62ca0d0

**Comment by ArtofWASD** [comment]
Давно пора закрыть
